name: Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor
        env:
          # Non-secret config (from Repository Variables)
          PROVIDER: ${{ vars.PROVIDER }}                    # boomnow_http
          ALERT_COOLDOWN_MINUTES: ${{ vars.ALERT_COOLDOWN_MINUTES }}
          OFFLINE_GRACE_MINUTES: ${{ vars.OFFLINE_GRACE_MINUTES }}
          BATTERY_LOW_THRESHOLD: ${{ vars.BATTERY_LOW_THRESHOLD }}
          BOOMNOW_BASE_URL: ${{ vars.BOOMNOW_BASE_URL }}
          BOOMNOW_DEVICES_ENDPOINT: ${{ vars.BOOMNOW_DEVICES_ENDPOINT }}

          # Secrets (credentials)
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAILS: ${{ secrets.TO_EMAILS }}
          BOOMNOW_API_KEY: ${{ secrets.BOOMNOW_API_KEY }}          # leave empty if not used
          BOOMNOW_AUTH_HEADER: ${{ secrets.BOOMNOW_AUTH_HEADER }}
          BOOMNOW_COOKIE: ${{ secrets.BOOMNOW_COOKIE }}
          BOOMNOW_USERNAME: ${{ secrets.BOOMNOW_USERNAME }}        # using Basic auth
          BOOMNOW_PASSWORD: ${{ secrets.BOOMNOW_PASSWORD }}
        run: |
          python - <<'PY'
          from app.main import main
          main()
          PY
